import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import * as fonts from './fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Hackerhouse',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => (
  <html>
    <body className={cn('dark', fonts.literata.variable, fonts.inter.variable, fonts.jetbrainsMono.variable)}>
      <main className='mx-auto min-h-dvh max-w-md sm:border-x sm:border-solid sm:border-border'>{children}</main>
    </body>
  </html>
);

export default Layout;
